general:
  general:
    backend: default
    imshow_origin: upper
    zoom_around_mask: true
mat_wrap:
  Cmap:
    figure:
      cmap: default
      linscale: 2.0
      linthresh: 1.0
      norm: linear
      vmax: null
      vmin: null
    subplot:
      cmap: default
      linscale: 2.0
      linthresh: 1.0
      norm: linear
      vmax: null
      vmin: null
  Colorbar:
    figure:
      fraction: 3.0
      pad: 4.0
    subplot:
      fraction: 0.1
      pad: 0.2
plots:
  fits_are_zoomed: true
  dataset:
    subplot_dataset: true
  fit:
    subplot_fit: true
    subplot_of_galaxies: false
    fits_fit: true
    fits_galaxy_images : true
    fits_model_galaxy_images : true
  fit_imaging: {}
  fit_interferometer:
    fits_dirty_images: true
  fit_quantity:
    subplot_fit: false
  adapt:
    subplot_adapt_images: true
  inversion:
    subplot_inversion: true
    csv_reconstruction: true
  galaxies:
    subplot_galaxies: true
    subplot_galaxy_images: true
    fits_galaxy_images: true
  positions:
    image_with_positions: true
