general:
  backend: default
  imshow_origin: upper
  zoom_around_mask: true
inversion:
  reconstruction_vmax_factor: 0.5
zoom:
  plane_percent: 0.01
  inversion_percent: 0.01
colormap: autoarray
ticks:
  extent_factor_2d: 0.75
  number_of_ticks_2d: 3
contour:
  total_contours: 10
  include_values: false
colorbar:
  fraction: 0.047
  pad: 0.01
  labelrotation: 90
  labelsize: 22
  labelsize_subplot: 18