TangentialCriticalCurvesPlot:
  figure:
    c: w
    linestyle: '-'
    linewidth: 2
  subplot:
    c: w
    linestyle: '-'
    linewidth: 2
TangentialCausticsPlot:
  figure:
    c: w
    linestyle: '-'
    linewidth: 2
  subplot:
    c: w
    linestyle: '-'
    linewidth: 2
RadialCriticalCurvesPlot:
  figure:
    c: y
    linestyle: '-'
    linewidth: 2
  subplot:
    c: y
    linestyle: '-'
    linewidth: 2
RadialCausticsPlot:
  figure:
    c: y
    linestyle: '-'
    linewidth: 2
  subplot:
    c: y
    linestyle: '-'
    linewidth: 2    
LightProfileCentresScatter:
  figure:
    c: k,r,g,b,m,y
    marker: +
    s: 20
  subplot:
    c: r,g,b,m,y,k
    marker: +
    s: 26
MassProfileCentresScatter:
  figure:
    c: k,r,g,b,m,y
    marker: x
    s: 20
  subplot:
    c: r,g,b,m,y,k
    marker: x
    s: 26
MultipleImagesScatter:
  figure:
    c: k,r,g,b,m,y
    marker: o
    s: 16
  subplot:
    c: r,g,b,m,y,k
    marker: o
    s: 16
