KMeans:
  pixels:
    type: Uniform
    lower_limit: 50.0
    upper_limit: 2500.0
    width_modifier:
      type: Absolute
      value: 100.0
    gaussian_limits:
      lower: 50.0
      upper: inf
  weight_floor:
    type: LogUniform
    lower_limit: 0.00001
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.1
    gaussian_limits:
      lower: 0.0
      upper: inf
  weight_power:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 5.0
    gaussian_limits:
      lower: 0.0
      upper: inf