Overlay:
  shape_0:
    type: Uniform
    lower_limit: 20.0
    upper_limit: 45.0
    width_modifier:
      type: Absolute
      value: 8.0
    gaussian_limits:
      lower: 3.0
      upper: inf
  shape_1:
    type: Uniform
    lower_limit: 20.0
    upper_limit: 45.0
    width_modifier:
      type: Absolute
      value: 8.0
    gaussian_limits:
      lower: 3.0
      upper: inf