Chameleon:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    width_modifier:
      type: Absolute
      value: 0.05
    limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    width_modifier:
      type: Absolute
      value: 0.05
    limits:
      lower: -inf
      upper: inf
  core_radius_0:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.3
    limits:
      lower: 0.0
      upper: inf
  core_radius_1:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.3
    limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: TruncatedGaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: TruncatedGaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    limits:
      lower: -1.0
      upper: 1.0
ChameleonSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    width_modifier:
      type: Absolute
      value: 0.05
    limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.3
    width_modifier:
      type: Absolute
      value: 0.05
    limits:
      lower: -inf
      upper: inf
  core_radius_0:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.3
    limits:
      lower: 0.0
      upper: inf
  core_radius_1:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.3
    limits:
      lower: 0.0
      upper: inf
