ExternalShear:
  gamma_1:
    type: Uniform
    lower_limit: -0.2
    upper_limit: 0.2
    width_modifier:
      type: Absolute
      value: 0.05
    limits:
      lower: -inf
      upper: inf
  gamma_2:
    type: Uniform
    lower_limit: -0.2
    upper_limit: 0.2
    width_modifier:
      type: Absolute
      value: 0.05
    limits:
      lower: -inf
      upper: inf
