PowerLawCore:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    width_modifier:
      type: Absolute
      value: 0.05
    limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    width_modifier:
      type: Absolute
      value: 0.05
    limits:
      lower: -inf
      upper: inf
  core_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.2
    width_modifier:
      type: Absolute
      value: 0.1
    limits:
      lower: 0.0
      upper: inf
  einstein_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 8.0
    width_modifier:
      type: Relative
      value: 0.25
    limits:
      lower: 0.0
      upper: inf
  ell_comps_0:
    type: TruncatedGaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    limits:
      lower: -1.0
      upper: 1.0
  ell_comps_1:
    type: TruncatedGaussian
    mean: 0.0
    sigma: 0.3
    lower_limit: -1.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
    limits:
      lower: -1.0
      upper: 1.0
  slope:
    type: Uniform
    lower_limit: 1.5
    upper_limit: 3.0
    width_modifier:
      type: Absolute
      value: 0.2
    limits:
      lower: 1.0
      upper: 3.0
PowerLawCoreSph:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    width_modifier:
      type: Absolute
      value: 0.05
    limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.1
    width_modifier:
      type: Absolute
      value: 0.05
    limits:
      lower: -inf
      upper: inf
  core_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 0.2
    width_modifier:
      type: Absolute
      value: 0.1
    limits:
      lower: 0.0
      upper: inf
  einstein_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 8.0
    width_modifier:
      type: Relative
      value: 0.25
    limits:
      lower: 0.0
      upper: inf
  slope:
    type: Uniform
    lower_limit: 1.5
    upper_limit: 3.0
    width_modifier:
      type: Absolute
      value: 0.2
    limits:
      lower: 1.0
      upper: 3.0
